# Spring boot application
spring:
  application:
    name: spring-boot-module-provider-application
  # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: org.apache.dubbo.spring.boot.sample.provider.service
  protocol:
    name: ${spring.application.name}
    port: 12345
  registry:
    address: zookeeper://localhost:2181
